title: "Rate My Facilities"
description: "A site providing helpful information on good facilities around campus."
google_analytics:
  show_downloads: true
theme: jekyll-theme-minima

gems:
  - jekyll-mentions
